/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AntCarousel: typeof import('antd')['Carousel']
  const AntDivider: typeof import('antd')['Divider']
  const AntLayout: typeof import('antd')['Layout']
  const Button: typeof import('antd')['Button']
  const Carousel: typeof import('../shared/components')['Carousel']
  const Col: typeof import('antd')['Col']
  const ConfigProvider: typeof import('antd')['ConfigProvider']
  const DashboardLayout: typeof import('../shared/components')['DashboardLayout']
  const Flex: typeof import('antd')['Flex']
  const Header: typeof import('../shared/components')['Header']
  const Helmet: typeof import('react-helmet-async')['Helmet']
  const HelmetProvider: typeof import('react-helmet-async')['HelmetProvider']
  const Input: typeof import('antd')['Input']
  const Link: typeof import('react-router-dom')['Link']
  const NavLink: typeof import('react-router-dom')['NavLink']
  const Outlet: typeof import('react-router-dom')['Outlet']
  const RouterProvider: typeof import('react-router-dom')['RouterProvider']
  const Row: typeof import('antd')['Row']
  const StrictMode: typeof import('react')['StrictMode']
  const Suspense: typeof import('react')['Suspense']
  const Tabs: typeof import('antd')['Tabs']
  const Trans: typeof import('react-i18next')['Trans']
  const Translation: typeof import('react-i18next')['Translation']
  const cloneElement: typeof import('react')['cloneElement']
  const createBrowserRouter: typeof import('react-router-dom')['createBrowserRouter']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const lazy: typeof import('react')['lazy']
  const lazyload: typeof import('../shared/components')['lazyload']
  const lazyloadWithLoader: typeof import('../shared/components')['lazyloadWithLoader']
  const map: typeof import('lodash-es')['map']
  const memo: typeof import('react')['memo']
  const range: typeof import('lodash-es')['range']
  const startTransition: typeof import('react')['startTransition']
  const subtract: typeof import('lodash-es')['subtract']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useParams: typeof import('react-router-dom')['useParams']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { TabsProps } from 'antd'
  // @ts-ignore
  export type { FunctionComponent, ReactNode, Key, ComponentType, ComponentProps, Ref } from 'react'
}
